version: '3.9'

services:
  app:
    build: .
    container_name: express-ddd-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/app"
      NODE_ENV: production
      APP_PORT: 3000
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && node dist/main.js"

  db:
    image: postgres:15-alpine
    container_name: express-ddd-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
